export function capitalize(name: string) {
    return name
        .split("")
        .map((item, index) => (index === 0 ? item.toUpperCase() : item))
        .join("");
}

export function showHelp() {
    console.log(`
EMG — Easy Module Generator

** Please define the file extension **

USAGE
  emg -g <module> -f <name> => generates file inside ./src/<module>/<name>
  emg -f <name> => generates file inside ./src

MODULES
  controller   c
  routes       r
  middleware   m
  errors       e
  services     s

OPTIONS
  -g, --generate   Module type
  -f, --file       File name
  -h, --help       Show help
`);
}

export function argParse(flag: string): string | undefined {
    const allArgs = process.argv.slice(2);
    let flagIndex = allArgs.indexOf(flag)

    if (flagIndex === -1) {
        const alternateFlag = `-${flag.split("-").filter(Boolean)[0][0].toLowerCase()}`
        const alternateFlagIndex = allArgs.indexOf(alternateFlag);
        if (alternateFlagIndex === -1) {
            return undefined;
        }
        flagIndex = alternateFlagIndex;
    }

    const value = allArgs[flagIndex + 1];

    if (!value || value.startsWith("-")) {
        return undefined;
    }

    return value;
}

export function resolveType(type: string) {
    switch (type) {
        case "controller":
        case "c":
            return "controller";
        case "service":
        case "s":
            return "service";
        case "middleware":
        case "m":
            return "middleware";
        case "routes":
        case "r":
            return "routes";
        case "errors":
        case "e":
            return "errors";
    }
}

export function generateFileContent(type: string, fileName: string) {
    const name = fileName.split(".")[0];
    const capitalizeName = capitalize(name);
    if (!type) {
        return `
export function ${name}() {
    console.log("generated by emg");
}
`
    }
    switch (type) {
        case "controller":
        case "c":
            return `
export class ${capitalizeName}{
    public foo;
    constructor(foo: string) {
        this.foo = foo;
    }
    public foobar() {
        console.log("generated by emg");
    }
}`;

        case "middleware":
        case "m":
            return `
    export function ${name}() {
        console.log("generated by emg");
    }
}`;
        case "routes":
        case "r":
            return `
const ${name}Router = Router();
postRouter.get('/', (req, res) => res.send("generated by emg"));
export default ${name}Router;
`;
        case "errors":
        case "e":
            return `
export class BaseError extends Error {
  public statusCode: number;

  constructor(message: string, statusCode: number) {
    super(message);
    this.statusCode = statusCode;
    Object.setPrototypeOf(this, new.target.prototype);
    Error.captureStackTrace(this);
  }
}

export class NotFoundError extends BaseError {
  constructor(message: string = 'Resource not found') {
    super(message, 404);
    this.name = 'NotFoundError';
  }
}

export class BadRequestError extends BaseError {
  constructor(message: string = 'Bad request') {
    super(message, 404);
    this.name = 'BadRequestError';
  }
}

export class TooManyRequestError extends BaseError {
  constructor(message: string = 'Too many request, please try again later') {
    super(message, 429);
    this.name = 'TooManyRequestError';
  }
}

export class ConflictError extends BaseError {
  constructor(message: string = 'Conflict Error') {
    super(message, 409);
    this.name = 'ConflictError';
  }
}

export class ValidationError extends BaseError {
  constructor(message: string = 'Invalid input') {
    super(message, 400);
    this.name = 'ValidationError';
  }
}

export class UnauthorizedError extends BaseError {
  constructor(message: string = 'Unauthorized') {
    super(message, 401);
    this.name = 'UnauthorizedError';
  }
}

export class MailError extends BaseError {
  constructor(message: string = 'Error while sending the mail') {
    super(message, 500);
    this.name = 'MailError';
  }
}

export class PrismaError extends BaseError {
  constructor(message: string = 'Database Error: Prisma') {
    super(message, 500);
    this.name = 'PrismaError';
  }
}
`;
        case "services":
        case "s":
            return `
export default class ${capitalizeName}Service {
  public static async FindById() {
  }

  public static async Create() {
  }

  public static async Update() {
  }

  public static async Delete() {
  }
`;
    }
}
